### ISSUE TITLE
Dependencies Unresolved

### ISSUE THREAD

**Issue by deprov447** [awknoman/ASCII-Face-Generator#1]
Magick++.h not found...
One has to install imagemagick package first...
`sudo apt-get install libmagick++-dev`

**Comment by deprov447** [comment]
program.out isn't executable by default.
`sudo chmod +x program.out`

**Comment by yasht01** [comment]
Thanks for the help. I will update it in the readme.

**Comment by deprov447** [comment]
Saw the readme. Try learning markdown and format the readme well. Just an Advice.
